### ISSUE TITLE
CSS files not working

### ISSUE THREAD

**Issue by rawris** [adarshsingh1407/neo-cra#1]
I have tried to move my client side project to server side using your seed project but imported css files in components throws error

**Comment by adarshsingh1407** [comment]
Hi @rawris 

Yes, currently this project does not support importing CSS in Components. However, you can still use your old CSS files by importing them in 'src/index.js'.

_Solution_: **You'll have to import all your CSS files the same way as 'index.css' has been imported in 'src/index.js', instead of importing them in their respective components**.

I have been busy working on supporting code-splitting with SSR in my spare time. After that, I'll move on to HMR. And my aim is to bring in _css-splitting_ along with _js-splitting_ when I'm done with _code-splitting with SSR_ (currently on my TODO list).

![screen shot 2017-12-18 at 1 56 49 pm](https://user-images.githubusercontent.com/6937549/34097044-a07de716-e3fd-11e7-81db-2e890d686330.png)

P.S. If you wish to contribute to this project, you are welcome to do so.
